# Generated by Django 4.2.10 on 2024-03-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0002_doctor_user_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                ],
                default="patient",
                max_length=10,
            ),
        ),
    ]
