# Generated by Django 4.2.10 on 2024-03-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0003_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("appointment", "Appointment"),
                ],
                default="appointment",
                max_length=15,
            ),
        ),
    ]
