# Generated by Django 4.2.10 on 2024-03-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0004_alter_appointment_doctor_alter_customuser_user_type"),
    ]

    operations = [
        migrations.DeleteModel(name="Appointment",),
    ]
