# Generated by Django 4.2.10 on 2024-03-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0005_delete_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("general_health", "General Health"),
                            ("cardiology", "Cardiology"),
                            ("dental", "Dental"),
                            ("medical_research", "Medical Research"),
                        ],
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("message", models.TextField()),
            ],
        ),
    ]
