# Generated by Django 4.2.10 on 2024-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0006_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_patient",
            field=models.BooleanField(default=False),
        ),
    ]
