# Generated by Django 4.2.10 on 2024-03-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0007_customuser_is_doctor_customuser_is_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="password",
            field=models.CharField(default="some_default_value", max_length=50),
        ),
    ]
