# Generated by Django 4.2.10 on 2024-03-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0008_doctor_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
