# Generated by Django 4.2.10 on 2024-03-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0009_user_is_doctor"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="is_doctor",),
        migrations.RemoveField(model_name="customuser", name="is_patient",),
    ]
