# Generated by Django 4.2.10 on 2024-03-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0010_remove_customuser_is_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("patient", "patient"),
                ],
                default="appointment",
                max_length=15,
            ),
        ),
    ]
