# Generated by Django 4.2.10 on 2024-03-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0016_alter_doctor_user_alter_doctor_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="doctor", unique_together=set(),),
    ]
