# Generated by Django 4.2.10 on 2024-03-11 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0018_alter_doctor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                default=50,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
