# Generated by Django 4.2.10 on 2024-03-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0022_alter_doctor_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="doctor", name="user",),
        migrations.AddField(
            model_name="doctor",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("patient", "patient"),
                ],
                default="patient",
                max_length=15,
            ),
        ),
    ]
